import { jsPDF } from 'jspdf';
import { TitleReportData } from '@/lib/agents/title-search/types';

export async function generateTitleReportPDF(data: TitleReportData): Promise<Buffer> {
  const doc = new jsPDF();
  let y = 20;
  const lineHeight = 7;
  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - (margin * 2);

  // Helper for text wrapping
  const addWrappedText = (text: string, fontSize: number, fontStyle: string = 'normal') => {
    doc.setFontSize(fontSize);
    doc.setFont('helvetica', fontStyle);
    const lines = doc.splitTextToSize(text, contentWidth);
    doc.text(lines, margin, y);
    y += (lines.length * lineHeight * (fontSize / 12));
  };

  const addLine = () => { y += lineHeight; };

    // Header
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('Title AI Report', pageWidth / 2, y, { align: 'center' });
    y += 15;

  // Property Info
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Report Date: ${data.reportDate}`, pageWidth - margin, y, { align: 'right' });
  y += 10;

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Property Information', margin, y);
  y += 10;

  addWrappedText(`Address: ${data.propertyAddress}`, 12);
  if (data.parcelId) addWrappedText(`Parcel ID: ${data.parcelId}`, 12);
  addWrappedText(`County: ${data.county}`, 12);
  if (data.legalDescription) addWrappedText(`Legal Description: ${data.legalDescription}`, 12);
  addLine();

  // Executive Summary
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Executive Summary', margin, y);
  y += 10;
  addWrappedText(data.summary, 11);
  addLine();

  // Ownership Chain
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Chain of Title (Ownership History)', margin, y);
  y += 10;

  data.ownershipChain.forEach((node, index) => {
    addWrappedText(`${index + 1}. ${node.date} - ${node.documentType}`, 11, 'bold');
    addWrappedText(`Grantor: ${node.grantor}`, 10);
    addWrappedText(`Grantee: ${node.grantee}`, 10);
    if (node.documentNumber) addWrappedText(`Doc #: ${node.documentNumber}`, 10);
    y += 5; // Extra spacing
    if (y > 270) { doc.addPage(); y = 20; }
  });
  addLine();

  // Liens
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Active Liens & Encumbrances', margin, y);
  y += 10;

  if (data.liens.length === 0) {
    addWrappedText('No active liens detected.', 11, 'italic');
  } else {
    data.liens.forEach(lien => {
      if (lien.priority === 'High') doc.setTextColor(255, 0, 0);
      addWrappedText(`${lien.type} Lien - ${lien.status}`, 11, 'bold');
      doc.setTextColor(0, 0, 0);
      addWrappedText(`Claimant: ${lien.claimant}`, 10);
      if (lien.amount) addWrappedText(`Amount: ${lien.amount}`, 10);
      addWrappedText(`Recorded: ${lien.dateRecorded}`, 10);
      if (lien.description) addWrappedText(`Details: ${lien.description}`, 10);
      y += 5;
      if (y > 270) { doc.addPage(); y = 20; }
    });
  }
  addLine();

  // Exceptions
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Exceptions & Risks', margin, y);
  y += 10;

  if (data.exceptions.length === 0) {
    addWrappedText('No major exceptions identified.', 11, 'italic');
  } else {
    data.exceptions.forEach(ex => {
      addWrappedText(`${ex.type}: ${ex.description}`, 11, 'bold');
      addWrappedText(ex.explanation, 10);
      if (ex.remedy) addWrappedText(`Potential Remedy: ${ex.remedy}`, 10, 'italic');
      y += 5;
      if (y > 270) { doc.addPage(); y = 20; }
    });
  }
  
  // Disclaimer
  y = 270;
  if (y > 270) { doc.addPage(); y = 270; }
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  const disclaimer = 'DISCLAIMER: This report is generated by AI and is for informational purposes only. It does not constitute a legal title opinion or title insurance. Homestand AI is not a title company or law firm. Please verify all information with official county records or a licensed professional.';
  const discLines = doc.splitTextToSize(disclaimer, contentWidth);
  doc.text(discLines, pageWidth / 2, y, { align: 'center' });

  // Output as buffer
  return Buffer.from(doc.output('arraybuffer'));
}
